module.exports = {
  DIALOGFLOWCX_PROJECT_ID: 'DIALOGFLOWCX_PROJECT_ID',
  DIALOGFLOWCX_LOCATION: 'DIALOGFLOWCX_LOCATION',
  DIALOGFLOWCX_AGENT_ID: 'DIALOGFLOWCX_AGENT_ID',
  DIALOGFLOWCX_ENVIRONMENT: 'DIALOGFLOWCX_ENVIRONMENT',
  DIALOGFLOWCX_CLIENT_EMAIL: 'DIALOGFLOWCX_CLIENT_EMAIL',
  DIALOGFLOWCX_PRIVATE_KEY: 'DIALOGFLOWCX_PRIVATE_KEY',
  DIALOGFLOWCX_LANGUAGE_CODE: 'DIALOGFLOWCX_LANGUAGE_CODE',
  DIALOGFLOWCX_QUERY_PARAMS: 'DIALOGFLOWCX_QUERY_PARAMS',
  DIALOGFLOWCX_WELCOME_TEXT: 'DIALOGFLOWCX_WELCOME_TEXT',
  DIALOGFLOWCX_USE_FALLBACK: 'DIALOGFLOWCX_USE_FALLBACK',
  DIALOGFLOWCX_TIMEOUT: 'DIALOGFLOWCX_TIMEOUT'
}
